### ISSUE TITLE
Question to opencore and Linux and some other questions and issues

### ISSUE THREAD

**Issue by DomiDomian** [XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4#3] opened 2021-02-21 21:48 UTC
ok, i was trying around alot and checked my battery time. With normal use and multiple reboots a got operating time of a bit more of 4 hours, i think without rebooting so many times 5 hours could be realistic

so, now i can boot Windows with opencore, no more problems because your acpis have those if osi darwin string in it. my old own repo did not have, so i always crashed windows in acpi failure. this was the main cause why i switched to your repo and your acpis are much newer than my ones based on rehabman
![21213507](https://user-images.githubusercontent.com/79382625/108639789-9f368980-7496-11eb-96d1-28f47892dc1d.png)
my only problem now is booting linux Mint and opensuse with opencore. -it does not work, i get to the grub bootloader screen but it won´t boot. i think something is injected, maybe acpi tables where those darwin string is not inside???? did not find a solution, but internet shows that many people have the same problem. maybe you have a solution

in all kind of forums you can read that it never will be possible to get a working trackpoint, but since today i am not sure if this is true, because by loading voodoops2mouse it works, was a big surprise for me ;) -i think we should work on it

one last issue i have, after sleep the cardreader does not initialize anymore, the same like in my old repo

Thank you very much, now i think my efi is way more clean and  advanced like before

**Comment by XXCoreRangerX** [comment] 2021-02-22 08:03
Hey, thank you for being so active! I look forward to work on this EFI with you!

I haven't tried booting Linux on this laptop before. Would be awesome to have it working. I'll look into it tomorrow and I'll let you know if I succeed - today is quite a busy day for me. If you find any solutions, feel free to make a commit and a pull request.

The trackpoint is an **PS2** device. I think the kext breaks the touchpad, because it's a device that can work both on **SMBus and PS2**. On the `VoodooRMI` repo, it's recommended to **not inject** `VoodooPS2Mouse`. I think it **would** be possible to have both trackpoint and touchpad working, but `VoodooPS2Mouse` would have to **ignore the touchpad**, and only **enable the trackpoint**.

For the card reader, make sure you're using **Sinetek-rtsx by cholonam**. Adding boot args like `-rtsx_mimic_linux` and/or `rtsx_sleep_wake_delay_ms=1000` may fix the card reader after sleep.

**Comment by XXCoreRangerX** [comment] 2021-03-15 17:14
> my only problem now is booting linux Mint and opensuse with opencore. -it does not work, i get to the grub bootloader screen but it won´t boot.

I’m having the same issue. I tried modifying all SSDTs and even disabling them with no success. Linux verbose doesn’t show anything because it can’t even load the kernel. 

Pretty sure OpenCore is injecting some stuff into Linux making it unbootable. 

I think the only way you can solve this is use rEFInd for booting Windows, macOS (OpenCore->macOS) and Linux.

**Comment by DomiDomian** [comment] 2021-03-15 17:34
Hi thank you for testing out, when I boot linux I directly boot via F9 key. there is a nice windows tool called Bootice, there you can.manage your bios boot entries very easy. so not a big deal, hope in future OC will support Linux.
![Bootice_12](https://user-images.githubusercontent.com/79382625/111195813-f1158f80-85bc-11eb-822f-7e5a8fd5d3f1.png)
with refind I had no success, it always says something like Volume icons and then a size, but did not try much with it.

**Comment by XXCoreRangerX** [comment] 2021-03-16 09:41
Yeah, I think we can't do anything about it. 

However, I got some [more info on the trackpoint](https://github.com/VoodooSMBus/VoodooSMBus/issues/66). I talked to the developer of VoodooRMI and tried to solve this. Unfortunately we couldn't do anything, because the problem is with VoodooPS2Controller, not VoodooRMI. This is quite complicated but it definitely can be fixed.

Also, does the card reader work on your laptop with those patches now? For my machine all I had to do is use `-rtsx_mimic_linux` boot arg to initialize it after wake from sleep.

**Comment by DomiDomian** [comment] 2021-03-16 11:23
Great! it works, now I completely switched to your efi made some changes for my external hardware and co. now after sleep SD Card is available. At the moment I work on other projects, I got some hp 6570b´s made some hardware repairs and Bios Unlocking. Followed this very interesting tutorial: https://www.eevblog.com/forum/general-computing/new-way-to-reset-laptop-bios-passwords-(probook-6570b-successful-unlock!!!)/

**Comment by DomiDomian** [comment] 2021-03-16 11:28
for some HP 6570b I installed BigSur and used the tool from Chris https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator-OC

It's amazing after installing everything works fine and the config.plist is so clean, not even one patch to find, all inside dsdt. Great for such an old machine!

**Comment by XXCoreRangerX** [comment] 2021-03-24 14:19
Good job! However, DSDT patching isn't actually better than using SSDTs. SSDTs are always **less bloated**. I use multiple different SSDTs in EFI for this laptop, so it's easy to find out what patches are required here. Keeping them all in a single SSDT or a patched DSDT would make it harder to reverse engineer ACPI.

_I'm gonna close this issue, assuming all the issues here except booting Linux are solved. I think it's a problem on the OpenCore side but I'm gonna keep working on it._

**Closed by XXCoreRangerX** 2021-03-24 14:19 UTC
Labels: Enhancement
